---
- name: "Restart application"
  systemd:
    name: "{{ springboot_application_name }}"
    enabled: yes
    daemon-reload: yes
    state: restarted
  when: use_system_d

#- name: "restart sprinbootapp"
#  service:
#    name: "{{ springboot_application_name }}"
#    state: started
#    enabled: yes
#  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
